
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: root
  #password: clipper123
  #socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: signals
